__title__ = 'fasthttp'
__description__ = 'Fast Http'
__url__ = 'https://github.com/MarcosVs98/Fast-HTTP'
__version__ = '1.0.0'
__build__ = 0x022300
__author__ = 'Marcos Vinicios '
__author_email__ = 'marcosvs@protonmail.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2020 '