from fastRequest import HTTPRequest

def http_session(
            method,
            url,
            headers=None,
            cookies=None,
            redirects=None,
            ax_redirects=None,
            auth=None,
            timeout=None,
            postdata=None,
            proxy=None,
            luminati=False,
            proxy_user=None,
            proxy_auth=None,
            proxy_pass=None,
            proxy_headers=None,
            son=None,
            params=None,
            skip_auto_headers=None,
            ssl=True,
            sslcontext=None,
            verify_ssl=True,
            raise_for_status=False
):
	response = HTTPRequest(
                            method,
                            url,
                            headers,
                            cookies,
                            redirects,
                            ax_redirects,
                            auth,
                            timeout,
                            postdata,
                            proxy,
                            luminati,
                            proxy_user,
                            proxy_auth,
                            proxy_pass,
                            proxy_headers,
                            son,
                            params,
                            skip_auto_headers,
                            ssl,
                            sslcontext,
                            verify_ssl,
                            raise_for_status)
	return response.result()